Dev yoshiki
cta-observatory/ctapipe_io_magic pull request #12
Opened 2022-01-06 10:34 UTC by YoshikiOhtani

I created a custom trigger container so that the `mjd`, `millisec`, `nanosec` parameters are obtained to keep the precision of the timestamps for the event coincidence algorithm. Then I updated some functions to store the parameters to the container. The uproot module dependency (requiring v0.4.x) is also updated.

2022-01-06 10:46 UTC, YoshikiOhtani commented
Sorry now I changed the destination of merge branch to master since Alessio suggested me to do so. It seems all the commits to update-ctapipe-v0.12 are merged to this branch, and so this pull request means that the modules in master branch can be only used in ctapipe v0.12.

2022-01-06 12:54 UTC, aleberti requested changes

2022-01-06 12:54 UTC, aleberti commented on ctapipe_io_magic/__init__.py
> +    # TelescopeTriggerContainer,
Simply remove this if not needed, no need to keep it as a comment.

2022-01-06 12:54 UTC, aleberti commented on ctapipe_io_magic/__init__.py
> +                )
Please do the same modifications also in _pedestal_event_generator.

2022-01-06 16:39 UTC, YoshikiOhtani commented
Hi @aleberti, thanks for the review, and I have just pushed a commit. Not only the pedestal event generator but I also modify the stereo event generator just in case, though I have not yet tested them. I will inform you if I find some problems.

By the way I think in general we can write the code more simply, but since we don't have time until the software school, I will try to simply them after the school.

2022-01-06 17:33 UTC, aleberti commented
> Hi @aleberti, thanks for the review, and I have just pushed a commit. Not only the pedestal event generator but I also modify the stereo event generator just in case, though I have not yet tested them. I will inform you if I find some problems.

Good, thank you 

> By the way I think in general we can write the code more simply, but since we don't have time until the software school, I will try to simply them after the school. 

Indeed yesterday I opened an issue on this #11. I will work on it in parallel to the preparation for the LST analysis school, I already have some code snippets I tested in the last days.

2022-01-07 09:36 UTC, aleberti approved these changes

2022-01-07 09:39 UTC, YoshikiOhtani commented
Hi @aleberti, thanks for the approval but can you please wait a bit to merge? Because I'm now implementing an idea to keep a precision of timestamps without creating the custom trigger container. I will push a new commit soon, so it would be appreciated if you could review it!

2022-01-07 09:40 UTC, aleberti commented
Tests are passing. I will merge the PR.

2022-01-07 09:40 UTC, merged

2022-01-07 09:42 UTC, aleberti commented
> Hi @aleberti, thanks for the approval but can you please wait a bit to merge? Because I'm now implementing an idea to keep a precision of timestamps without creating the custom trigger container. I will push a new commit soon, so it would be appreciated if you could review it!

sorry, I was too fast. but don't worry, simply open a new PR, I think it's also better to keep those separated since you are introducing a new implementation.

2022-01-07 09:43 UTC, YoshikiOhtani commented
You are faster :), but ok, I will open a new pull request.